version: 2.1

# If you only want circle to run on direct commits to master, you can uncomment this out
# and uncomment the filters: *filter-only-master down below too
#
aliases:
 - &filter-only-master
   branches:
     only:
       - master

commands:
  base-build-setup:
    steps:
      - run:
          name: Setup
          command: |
            sudo apt install -y --no-install-recommends g++ cmake libboost-all-dev

  build-tests-with-cmake:
    description: "Build SPARTA tests with CMake"
    steps:
      - run:
          name: Build
          command: |
            mkdir build
            cd build
            cmake ..
            cmake --build . -j 4

  run-all-tests:
    description: "Test SPARTA"
    steps:
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-results
            export GTEST_OUTPUT=xml:/tmp/test-results/
            cd build
            ./run_all_tests.sh
      - store_test_results:
          path: /tmp/test-results

jobs:
  build-deb_testing:
    docker:
      - image: circleci/buildpack-deps:testing
    resource_class: large
    steps:
      - checkout
      - base-build-setup
      - build-tests-with-cmake
      - run-all-tests

workflows:
  version: 2.1
  build:
    jobs:
      - build-deb_testing

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters: *filter-only-master
    jobs:
      - build-deb_testing
